version: "2"

linters:
  default: standard
  disable:
    - staticcheck  # too pedantic about error string capitalization
  enable:
    - misspell
    - unconvert
    - goconst
    - dupl
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true
