version: "2"

linters:
  default: standard
  disable:
    - staticcheck  # too pedantic about error string capitalization
  enable:
    - misspell
    - unconvert
    - goconst
    - dupl

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

run:
  timeout: 5m
  tests: true
