version: 2

project_name: gsca

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: gsca
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

brews:
  - repository:
      owner: zerkz
      name: gsca-brew
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/zerkz/gsca"
    description: "Global Steam Command Args - CLI tool to manage Steam game launch options"
    license: "MIT"
    install: |
      bin.install "gsca"

scoops:
  - repository:
      owner: zerkz
      name: gsca-scoop
      token: "{{ .Env.SCOOP_TAP_TOKEN }}"
    homepage: "https://github.com/zerkz/gsca"
    description: "Global Steam Command Args - CLI tool to manage Steam game launch options"
    license: "MIT"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: zerkz
    name: gsca
  draft: false
  prerelease: auto
  header: |
    ## GSCA {{ .Version }}

    Global Steam Command Args - CLI tool to manage Steam game launch options
  footer: |
    ### Installation

    **macOS (Homebrew):**
    ```bash
    brew install zerkz/gsca-brew/gsca
    ```

    **Windows (Scoop):**
    ```powershell
    scoop bucket add gsca https://github.com/zerkz/gsca-scoop.git
    scoop install gsca
    ```

    **Arch Linux (AUR):**
    ```bash
    yay -S gsca
    ```

    **Steam Deck / Linux (Flatpak):**
    ```bash
    flatpak install gsca-{{ .Version }}.flatpak
    ```

    **Manual (Linux/macOS):**
    ```bash
    tar -xzf gsca_{{ .Version }}_linux_amd64.tar.gz
    sudo mv gsca /usr/local/bin/
    ```
